name: Automate Stack Overflow login

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7,10,18 * * *"

jobs:
  login:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Login
        run: |
          python3 login.py
        env:
          STACKOVERFLOW_EMAIL: ${{ secrets.STACKOVERFLOW_USERNAME }}
          STACKOVERFLOW_PASSWORD: ${{ secrets.STACKOVERFLOW_PASSWORD }}